### ISSUE TITLE
Dashboard no showing the correct amount of devices

### ISSUE THREAD

**Issue by fpuigb** [Ubiquiti-Mobile/unifi-mobile-ios#11]
Controller reporting correct 2 WLAN  and 1 WAN devices but the APP shows 0 WLAN and 0 WAN devices on the top portion.

APP Version: 1.13 (11305)
Controller: 5.2.9
iOS: 10.1

![screen shot 2016-10-25 at 8 50 22 pm](https://cloud.githubusercontent.com/assets/23066292/19710097/b3cf3ec6-9af9-11e6-8c63-6741d5263a1d.png)
![fullsizeoutput_bd](https://cloud.githubusercontent.com/assets/23066292/19710100/bcde8530-9af9-11e6-89f8-e709828545a3.jpeg)

**Comment by Jonge** [comment]
Hey @fpuigb, the health overview in the iOS app only shows inactive/pending devices, because active devices are shown in the device chart. Might think about this to make it less confusing though.

**Comment by fpuigb** [comment]
Hi @Jonge  thanks for the clarification, I think would be a good idea if you can match the Ubiquiti dashboard adding the active devices in the green portion as well to avoid confusion. Nice job with the APP... Thanks...

**Comment by fpuigb** [comment]
Ok, I got it now. Its a good idea if you can match the controller to avoid confusion. But the APP is well done.

Thanks for the great work.

**Comment by Jonge** [comment]
The number of active devices has been added in the latest release. Closing.
