### ISSUE TITLE
Event search by name in the UniFi app not working

### ISSUE THREAD

**Issue by emilstahl** [Ubiquiti-Mobile/unifi-mobile-ios#14]
Currently you can't search by device name in the Event search in the UniFi app but only by MAC address.
![1](https://cloud.githubusercontent.com/assets/3885790/22667650/02953248-ecbe-11e6-8a92-8cd1de32b03f.PNG)
![2](https://cloud.githubusercontent.com/assets/3885790/22667651/04794ba8-ecbe-11e6-96e3-fc6a83605a42.PNG)

On th UniFi controller website you can search by device name. Event search by device name is missing in the UniFi app.
<img width="736" alt="screen" src="https://cloud.githubusercontent.com/assets/3885790/22667647/fe473f06-ecbd-11e6-94e5-e4502ee46002.png">

[Community forum thread](https://community.ubnt.com/t5/UniFi-Feature-Requests/Event-search-by-name-in-the-UniFi-app/idi-p/1826027)

**Comment by Jonge** [comment]
@emilstahl Thanks, I got the same report from support, maybe you talked to them already?

Anyway, the data is being parsed to clickable links only just when it gets displayed. So search currently works on unparsed data ("iPhone 7" is actually something like "User[00:00:00:00:00:00]" internally).

Will try to fix this soon.

**Comment by emilstahl** [comment]
@Jonge Yes, I talked to support, they told me I could submit a  feature request, so I did create an issue here.

And great!

**Comment by Jonge** [comment]
@emilstahl This should be fixed in the upcoming v2.3 beta.

Note that there are some performance issues when used on larger sites (hundreds of clients and thousands of events). I know how to optimize it but it will take some time, but I think it's good enough for the first version.

**Comment by emilstahl** [comment]
@Jonge Great! Fortunately my site is small.

I'm looking forward to try the beta.

**Comment by emilstahl** [comment]
Fixed in beta 😄🎉
![img_1411](https://cloud.githubusercontent.com/assets/3885790/22939657/b27867e4-f2df-11e6-8fbb-c6c2f5d28836.PNG)

**Comment by Jonge** [comment]
Wait, that's client list and not event list. :) But it should work there as well.

**Comment by emilstahl** [comment]
@Jonge Damn, you see fast! 👀

I fixed the mistanke right after I posted 😇
