### ISSUE TITLE
Nav bar overlays page

### ISSUE THREAD

**Issue by creemerica** [Ubiquiti-Mobile/unifi-mobile-ios#16]
When browsing to settings, the top nav bar overlays the page content. Testing on 7+ running iOS 11. 

![db5dd00a-0f00-433c-a636-37ab7b918115](https://user-images.githubusercontent.com/1232936/30192625-2e392560-940e-11e7-842d-eb679d5468d1.jpeg)
![4b9e6a2e-c9e1-4e6e-b031-05a4802c809f](https://user-images.githubusercontent.com/1232936/30192646-4acb6a58-940e-11e7-883f-1872495a52a9.jpeg)

**Comment by Jonge** [comment]
Thanks. This is a known issue that doesn't happen when built with Xcode 9 beta. Unfortunately, we can't yet submit builds using a beta version of Xcode, but I think next week it should be possible.

**Comment by creemerica** [comment]
Works great on latest iOS and iPhone X.

**Comment by Jonge** [comment]
Thanks for testing!
