### ISSUE TITLE
RX label incorrect 

### ISSUE THREAD

**Issue by larsbek** [Ubiquiti-Mobile/unifi-mobile-ios#18]
Not sure if this has been reported earlier, or if this is only in the danish translation. RX Retry / Dropped text is shown for both TX and RX traffic in Radio details pane on iOS Unifi app.
Shown below (first line should be TX Retry / Droppet I guess)
![74d475dd-02e3-4679-b3bc-178398d12d7c](https://user-images.githubusercontent.com/34555867/34016371-e92efb5a-e121-11e7-8b61-af5c37ae043c.jpeg)

Brgds, Lars

**Comment by Jonge** [comment]
Thanks @larsbek, this is only in the Danish translation. Fixed, should be fine in the next release.
