### ISSUE TITLE
Ports missing on USW-16-150W

### ISSUE THREAD

**Issue by koenkooi** [Ubiquiti-Mobile/unifi-mobile-ios#4]
The app will show less than 18 ports, it used to show 16, but after fiddling with aggregation it shows 17:
![img_6963](https://cloud.githubusercontent.com/assets/259525/17175904/6df978fc-540a-11e6-94bb-ebe427576425.PNG)

The web interface does show all 18 ports:

<img width="383" alt="schermafbeelding 2016-07-27 om 14 59 27" src="https://cloud.githubusercontent.com/assets/259525/17175974/ca6dbcec-540a-11e6-88fe-e92f5b74db7c.png">

**Comment by Jonge** [comment]
Thanks for the descriptive comment!

The problem is definitely with aggregated ports (it will show them as one). Will need to look at this.

**Comment by Jonge** [comment]
Tried to play a bit with port config but couldn't reproduce this issue. Found a couple bugs in port config though, not sure if it might be related -- does it happen only after changing it from the iOS app?

If anyone could provide a way to always replicate this problem, I would be very grateful.

**Comment by koenkooi** [comment]
I only change switch setting using the controller, not the ios app

**Comment by Jonge** [comment]
Ah got it, happens when two ports share the same name.

Will fix soon™.
