### ISSUE TITLE
Can't unblock device via Insights in 1.8.1 (1811) 

### ISSUE THREAD

**Issue by bcdouglas** [Ubiquiti-Mobile/unifi-mobile-ios#8]
Hi,

As of iOS build 1.8.1, I am no longer able to unblock a blocked device on the Insights "tab". The device correctly shows as "Blocked", but when I try to unblock, the device fades dims, the device "undims"...I never see the "Unblock" button come up from the bottom. I must log into my controller via a web browser to unblock the device. This has worked in previous builds. 

iOS: 9.3.3
App: 1.8.1 (1811)
Controller: 5.0.8

**Comment by Jonge** [comment]
Thanks for reporting, this is the only issue that has been fixed for release version only (one build higher - 1812, which is now on the App Store).

Didn't put it on beta because it was just a small fix.
